Case study references
Arbiter-WRTC/arbiter-wrtc.github.io pull request #1
Opened 2023-12-11 20:06 UTC by jayjayabose

references added

2023-12-12 21:47 UTC, watzmonium requested changes

2023-12-12 21:47 UTC, watzmonium commented on src/pages/case-study.md
> +When a client has a restrictive security configuration - like with a Symmetric NAT - the Traversal Using Relays around NAT (TURN) protocol (RFC 8656 [^5]) can be used by a server to relay that peer’s
can you update this one to be consistent with how #4 is formatted or vice-versa?

2023-12-13 15:00 UTC, jayjayabose commented
added references

2023-12-13 15:11 UTC, watzmonium approved these changes
Looks fantastic! This is almost done and I appreciate your hard work on this.

2023-12-13 15:11 UTC, merged